site_name: Universal Context-Free Solver
site_url: https://formallanguageconstrainedpathquerying.github.io/UCFS/
nav:
  - Home: index.md
  - DSL: dsl.md
  - Graphs: graphs.md
  - SPPF: sppf.md
  - Examples: usage-examples.md
theme:
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
